# -*- coding: utf-8 -*-
"""bitcoin-predictive-ml-pipeline

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ryqIu7TTMT7olmYhkuwOuTuiI2cbWGIM
"""

!pip install yfinance

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import yfinance as yf  # Tambahkan baris ini

df = yf.download('BTC-USD', start='2023-01-01', end='2026-09-01')

df = yf.download('BTC-USD', start='2023-01-01', end='2026-09-01')

# Add this in a new cell below the data acquisition step
df_features = df[['Close']].copy()

# 1. Add a 7-day Simple Moving Average (SMA)
df_features['SMA_7'] = df_features['Close'].rolling(window=7).mean()

# 2. Add a 14-day Relative Strength Index (RSI)
delta = df_features['Close'].diff()
gain = (delta.where(delta > 0, 0)).rolling(window=14).mean()
loss = (-delta.where(delta < 0, 0)).rolling(window=14).mean()
rs = gain / loss
df_features['RSI_14'] = 100 - (100 / (1 + rs))

# Create target variable and drop rows with empty values caused by indicators
df_features['Tomorrow_Price'] = df_features['Close'].shift(-1)
df_features.dropna(inplace=True)

print("Advanced features calculated successfully!")
df_features.head()

print("--- Bitcoin Dataset Sample ---")
df.head()

df_clean = df[['Close']].copy()

df_clean['Tomorrow_Price'] = df_clean['Close'].shift(-1)

df_clean.dropna(inplace=True)
print("Data cleaning completed!")

# Change this cell to use your new advanced features
X = df_features[['Close', 'SMA_7', 'RSI_14']].values
y = df_features['Tomorrow_Price'].values
print("Multi-feature matrix X and target y are ready!")

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(f"Training set: {X_train.shape[0]} days | Testing set: {X_test.shape[0]} days")

model = LinearRegression()
model.fit(X_train, y_train)
print("Machine Learning model training completed!")

y_pred = model.predict(X_test)
print("Prediction process complete.")

accuracy_score = r2_score(y_test, y_pred)
print(f"Model Accuracy (R2 Score): {accuracy_score:.4f}")

# Combine everything into one single cell
plt.figure(figsize=(10, 5))

# Use X_test[:, 0] to extract ONLY the 'Close' price column for the X-axis
plt.scatter(X_test[:, 0], y_test, color='gray', alpha=0.5, label='Actual Market Prices')
plt.scatter(X_test[:, 0], y_pred, color='red', alpha=0.6, s=15, label='AI Predicted Prices')

plt.title('Bitcoin Multi-Feature Price Prediction Model Evaluation')
plt.xlabel("Today's Close Price (USD)")
plt.ylabel("Tomorrow's Predicted Price (USD)")
plt.legend()
plt.grid(True)
plt.show()